name: CI build yarn project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 'v23.5.0'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

