name: CI build yarn project

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 'v23.5.0'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Release via rsync
        uses: D3rHase/rsync-deploy-action@latest
        with:
          HOST: vpn.visacheckk.com
          PORT: 22
          USER: tt
          PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          REPOSITORY_PATH: 'build'
          SERVER_PATH: '/home/tt/test'
