name: CI build yarn project

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 'v23.5.0'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # - name: Release via rsync
      #   uses: D3rHase/rsync-deploy-action@latest
      #   with:
      #     HOST: ${{ secrets.HOST }}
      #     PORT: 2212
      #     USER: ${{ secrets.USER }}
      #     PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
      #     REPOSITORY_PATH: 'build'
      #     SERVER_PATH: '/var/www/build'

      - name: setup
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          known_hosts: '${{ secrets.HOST }}'
          name: id_rsa-server
          config: |
            Host server
              HostName yyy.yyy.yyy.yyy
              User ${{ secrets.USER }}
              IdentityFile ~/.ssh/id_rsa-server
              Port ${{ secrets.PORT }}

      - name: rsync
        run: |
          ssh-keyscan -H ${{ secrets.HOST }}:${{ secrets.PORT }} >> ~/.ssh/known_hosts &&\
          rsync -avz ./build/ server:/home/tt/test -p ${{ secrets.PORT }}